---
pagetitle: "Matt Tansley" # Title for browser tab
format: # Required for multi-format publishing. Metadata for the formats is further defined in separate .yml files.
  html: default
  awesomecv-typst: default  
metadata-files:
  - html-settings.yml
  - awesomecv-typst-settings.yml
format-links: 
  - html
  - format: awesomecv-typst
    text: PDF
    icon: file-pdf
css: assets/css/cv-html.css   
---

::: {.content-visible when-format="html"}

::: {#html-cv-header .p-2}

[Matt Tansley]{.display-2}

[Software Engineer & Tester]{.lead}

:::

::: {#html-cv-header-contacts .d-flex .flex-column .flex-md-row .justify-content-center .p-2 .mb-5}

[{{< fa envelope >}} [matthew.tansley@protonmail.com](mailto:matthew.tansley@protonmail.com)]{.p-2}

[{{< fa brands github >}} [GitHub](https://github.com/Matt-Tansley)]{.p-2}

[{{< fa brands linkedin >}} [LinkedIn](https://www.linkedin.com/in/matthew-o-w-tansley/)]{.p-2}

:::

:::

## Summary

I am a dedicated and focused test engineer with experience in automation and performance testing, and a passion for continuous learning, especially in modern tools and best practices. I value collaborative environments where building strong relationships helps drive meaningful outcomes and shared success. I'm seeking a supportive and growth-oriented team culture where I can contribute my skills, learn from others, and help deliver high-quality software.

## Experience

### PartsTrader

**Test Engineer**, *May 2025 --- Present*

- Built and maintained a Cypress automated test suite for the new Invoices micro‑frontend, ensuring it is in-line with development standards and existing test suites.
- Supporting the use of Playwright across PartsTrader by contributing to the shared testing library, improving consistency, reuse, and long‑term maintainability while reducing duplicated effort between teams.
- Gained experience with C#/.NET, domain‑driven design, and PartsTrader microservice standards through collaboration with developers on my team.
- Developed a PowerShell email sender utility to automate RepairerStatement test scenarios, eliminating repetitive manual tasks and ensuring test repeatability.
- Built and containerised a dashboard using R, Docker, and AWS ECR to replace a manual Excel-based reporting process for RepairerStatement. This has significantly improved accessibility of results and reduced time spent updating a spreadsheet.
- Contributed to continuous improvement by facilitating a team retrospective.
- Demonstrated contributions to company culture and engagement by supporting the Summer of Tech Meet and Greet, volunteering as a fire warden, and organising the PartsTrader 2025 Dragon Boat team to build cross‑team collaboration in a social setting.

### Assurity Consulting

**Senior Test Engineer**, *October 2024 --- May 2025*

**Test Engineer**, *June 2021 --- October 2024*

- Maintained a large existing JMeter regression test suite covering a website, APIs, and authentication. As information was often scattered and incomplete, I took the initiative to consolidate existing documentation and create new material where it did not exist. This required gaining a deep understanding of the test suite, and close collaboration with team members and stakeholders to leverage their knowledge.
- Upskilled in k6, a modern JavaScript-based load testing tool, through a short-term project. I successfully learned and applied the new tool, and as a result the test suite was more maintainable and followed better software engineering practices compared to JMeter.
- Acted as a product owner for an internal project. Improved upon my skills of facilitation, prioritisation, and task management using Jira. Later, I joined a project that was tracking work in a spreadsheet; I introduced Jira and facilitated stand-ups, significantly improving collaboration and visibility.
- Collaborated closely with stakeholders to design realistic load test scenarios. While technical correctness is important, real-user feedback is important in understanding how a system truly operates. 
- Introduced automated report generation into our workflow using Quarto, improving consistency of visualisations and saving time by eliminating the need to manually create and copy-paste images. For example, one report that previously took 3 hours now takes under 30 minutes.
- Mentored and guided new team members joining the company, including helping more experienced colleagues upskill in tools used by our team such as GitHub Actions and our in-house cloud platform.
- Contributed to the graduate programme by preparing and delivering an introductory session on SQL and databases.
- Demonstrated keenness to continuously learn by obtaining certifications.

## Technical Skills

- **Languages:** JavaScript, HTML/CSS, C#/.NET, PowerShell, R, Bash, SQL
- **Testing Tools:** Playwright, Cypress, Insomnia & Postman, JMeter, k6
- **Other Tools:** GitHub Actions, AWS, Docker, Jira
- **Concepts:** Automation Testing, Agile, Performance Testing, Data Analysis, Data Visualisation 

## Personal Projects

**CV** [| [CV Website](https://matt-tansley.quarto.pub/cv/) | [GitHub Repo](https://github.com/Matt-Tansley/cv)]{.content-visible when-format="html"}

- Multi-format CV in HTML and PDF (Typst), using Quarto publishing engine.
- Deployment with GitHub Actions and hosted on Quarto Pub.

**Warhammer Rules Reference** [| [Netlify App](https://heresy-quick-reference.netlify.app/) | [GitHub Repo](https://github.com/Matt-Tansley/heresy-quick-reference)]{.content-visible when-format="html"}

- JS SvelteKit app to quickly and conveniently browse rules while playing. 
- Deployed and hosted on Netlify. 
- Used R to parse XML files for original data.

## Education and Certifications

**Education:** Bachelor of Commerce, Computer Science and Information Systems, Victoria University of Wellington

**Certifications:** AWS Certified Cloud Practitioner, ICAgile Certified Professional

## Interests

Yoga, Sourdough, Language Learning, Board Games, Travel, Film